ALTER TABLE scan_sessions
  ADD COLUMN IF NOT EXISTS event_tagline TEXT,
  ADD COLUMN IF NOT EXISTS registration_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS event_date DATE,
  ADD COLUMN IF NOT EXISTS event_timing TEXT,
  ADD COLUMN IF NOT EXISTS registration_start TEXT,
  ADD COLUMN IF NOT EXISTS venue TEXT,
  ADD COLUMN IF NOT EXISTS venue_field2 TEXT;
