ALTER TABLE items ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE items ADD COLUMN IF NOT EXISTS qr_email_sent_at TIMESTAMPTZ;
ALTER TABLE items ADD COLUMN IF NOT EXISTS qr_email_resend_id TEXT;
ALTER TABLE items ADD COLUMN IF NOT EXISTS qr_email_last_error TEXT;
